### ISSUE TITLE
Doesn't work for Windows XP

### ISSUE THREAD

**Issue by partyofocelots** [jborza/emuchip8me#3]
Hi, I don't really know if the program is available for Windows XP, but I can't use anything else for now, I also captured the error so it can be fixed.

![Zrzut ekranu z 2024-04-02 08-39-59](https://github.com/jborza/emuchip8me/assets/120318889/1dd0bba1-d074-4b65-acf9-e6fb7139a664)

**Comment by jborza** [comment]
Hi, I'll try to reproduce the issue.

**Comment by jborza** [comment]
Which service pack are you using? SP1, SP2, SP3?

**Comment by jborza** [comment]
Notification for myself:

JRE 1.4.2: https://www.oracle.com/java/technologies/java-archive-javase-v14-downloads.html#j2sdk-1.4.2_30-sol-JPR
WTK 2.1: https://www.oracle.com/java/technologies/java-archive-downloads-javame-downloads.html

**Comment by jborza** [comment]
OK, so I reproduced it in a local image. The problem is that I hard coded the path to the Java tools. To work around this problem, you can edit the path in the `build.bat` to wherever you installed the Java tool (the JRE).

```
set JAVAC=c:\tools\j2sdk1.4.2_19\bin\javac
set JAR=c:\tools\j2sdk1.4.2_19\bin\jar
```
I also found out that I forgot to mention that you need Python in the readme, will fix that as well.

**Comment by jborza** [comment]
I've also added the built emulator in the Releases page - https://github.com/jborza/emuchip8me/releases/tag/release

Have fun!

**Comment by jborza** [comment]
Done

**Comment by partyofocelots** [comment]
> Which service pack are you using? SP1, SP2, SP3?

I'm using Windows XP Media Center Edition (2005) on VirtualBox 

i wanted to make a reply before it was closed ;(

**Comment by jborza** [comment]
No problem, I'll reopen it

**Comment by partyofocelots** [comment]
> No problem, I'll reopen it

nonono it's fine

**Comment by jborza** [comment]
Anyway, it should be fixed - it was related to paths in the `build.bat`
